/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userpack;

import config.dbConnector;
import config.hashpass;
import config.session;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;
import javax.swing.JOptionPane;
import loginpack.login;

/**
 *
 * @author SCC-PC
 */
public class changepass extends javax.swing.JFrame {

    private String userRole;
    
    public changepass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        iddisplay = new javax.swing.JLabel();
        oldpass = new swing.TextField();
        newpass = new swing.TextField();
        connewpass = new swing.TextField();
        chgsucbut = new swing.Button();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(225, 223, 228));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(114, 114, 114));
        jLabel4.setText("ACCOUNT DETAILS ");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        iddisplay.setBackground(new java.awt.Color(255, 255, 255));
        iddisplay.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 35)); // NOI18N
        iddisplay.setForeground(new java.awt.Color(114, 114, 114));
        iddisplay.setText("(UID)");
        iddisplay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iddisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iddisplayMouseClicked(evt);
            }
        });
        jPanel1.add(iddisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        oldpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oldpass.setLabelText("Current Password");
        jPanel1.add(oldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 390, -1));

        newpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newpass.setLabelText("Enter New Password");
        jPanel1.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 390, -1));

        connewpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        connewpass.setLabelText("Confirm New Password");
        jPanel1.add(connewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 390, -1));

        chgsucbut.setBackground(new java.awt.Color(223, 120, 141));
        chgsucbut.setForeground(new java.awt.Color(114, 114, 114));
        chgsucbut.setText("Confirm");
        chgsucbut.setAutoscrolls(true);
        chgsucbut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chgsucbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chgsucbutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chgsucbutMouseExited(evt);
            }
        });
        chgsucbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chgsucbutActionPerformed(evt);
            }
        });
        jPanel1.add(chgsucbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 210, -1));

        jButton1.setText("cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1016, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

    }//GEN-LAST:event_jLabel4MouseClicked

    private void iddisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iddisplayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iddisplayMouseClicked

    private void chgsucbutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chgsucbutMouseEntered
        chgsucbut.setBackground(new java.awt.Color(205, 13, 50));
    }//GEN-LAST:event_chgsucbutMouseEntered

    private void chgsucbutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chgsucbutMouseExited
        chgsucbut.setBackground(new java.awt.Color(223,120,141));
    }//GEN-LAST:event_chgsucbutMouseExited

    private void chgsucbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chgsucbutActionPerformed
        try {
        dbConnector dbc = new dbConnector();
        session ses = session.getInstance();
        
        // Retrieve the user's current password and salt from the database
        String query = "SELECT u_password FROM tbl_users WHERE u_id = ?";
        ResultSet rs = dbc.getDataWithParams(query, ses.getUid());
        
        if (rs.next()) {
            String storedPassword = rs.getString("u_password");  // Format: salt:hashedPassword
            String[] parts = storedPassword.split(":");
            if (parts.length != 2) {
                JOptionPane.showMessageDialog(null, "Password format error in database.");
                return;
            }

            String storedSalt = parts[0];
            String storedHashedPassword = parts[1];

            // Verify the old password
            String oldHash = hashpass.hashWithSalt(oldpass.getText(), Base64.getDecoder().decode(storedSalt));
            if (!storedHashedPassword.equals(oldHash)) {
                JOptionPane.showMessageDialog(null, "Old Password is Incorrect!");
                return;
            }

            // Check if new password matches confirmation
            if (!newpass.getText().equals(connewpass.getText())) {
                JOptionPane.showMessageDialog(null, "New password and confirmation do not match!");
                return;
            }

            // Hash the new password
            String newHashedPassword = hashpass.hashPassword(newpass.getText());

            // Update the password in the database using a prepared statement to avoid SQL injection
            String updateQuery = "UPDATE tbl_users SET u_password = ? WHERE u_id = ?";
            dbc.updateDataWithParams(updateQuery, newHashedPassword, ses.getUid());

            // Success message and redirect to login
            JOptionPane.showMessageDialog(null, "Password Successfully Updated!");
            login lg = new login();
            lg.setVisible(true);
            this.dispose();
        }
    } catch (SQLException | NoSuchAlgorithmException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }

    }//GEN-LAST:event_chgsucbutActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        session ses = session.getInstance();
        
        iddisplay.setText("USER ID:"+ses.getUid());
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        usersdetails ud = new usersdetails();
        ud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changepass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button chgsucbut;
    public swing.TextField connewpass;
    private javax.swing.JLabel iddisplay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public swing.TextField newpass;
    public swing.TextField oldpass;
    // End of variables declaration//GEN-END:variables
}
