/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admindash;

import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Aubrey Rose Undang
 */
public class createuserforms extends javax.swing.JFrame {

    /**
     * Creates new form createuserforns
     */
    public createuserforms() {
        initComponents();
    }
    public static String email, usrname;
    
    public boolean duplicatedChecker() {
    dbConnector dbc = new dbConnector();
    try {
        String query = "SELECT u_email, u_username FROM tbl_users WHERE u_username = '" + uname.getText() + "' OR u_email = '" + eml.getText() + "'";
        ResultSet resultSet = dbc.getData(query);
        
        boolean duplicate = false; // Flag to track duplicates
        
        while (resultSet.next()) { // Loop through results (if any)
            email = resultSet.getString("u_email");
            usrname = resultSet.getString("u_username");
            
            if (email.equals(eml.getText())) {
                JOptionPane.showMessageDialog(null, "Email already used!");
                eml.setText("");
                duplicate = true;
            }
            
            if (usrname.equals(uname.getText())) {
                JOptionPane.showMessageDialog(null, "Username already used!");
                uname.setText("");
                duplicate = true;
            }
        }
        
        return duplicate;
    } catch (SQLException ex) {
        System.out.println("SQL Error: " + ex);
        return true; // Assume duplicate to avoid inserting problematic data
    }
}
    
    public boolean updateCheck() {
    dbConnector dbc = new dbConnector();
    
    String query = "SELECT u_email, u_username FROM tbl_users WHERE (u_username = '"+uname.getText()+"' OR u_email = '"+eml.getText()+"') AND u_id != '"+uid.getText()+"'";

    try {
        
        ResultSet resultSet = dbc.getData(query);

        while (resultSet.next()) {
            String existingEmail = resultSet.getString("u_email");
            String existingUsername = resultSet.getString("u_username");

            if (existingEmail.equals(eml.getText())) {
                JOptionPane.showMessageDialog(null, "Email is Already Used!");
                eml.setText("");
                return true;
            }
            if (existingUsername.equals(uname.getText())) {
                JOptionPane.showMessageDialog(null, "Username is Already Taken!");
                uname.setText("");
                return true;
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace(); // Print errors for debugging
    }
    return false;
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelBorder1 = new swing.PanelBorder();
        fname = new swing.TextField();
        lname = new swing.TextField();
        eml = new swing.TextField();
        uname = new swing.TextField();
        ps = new swing.PasswordField();
        role = new swing.Combobox();
        us = new swing.Combobox();
        uid = new swing.TextField();
        ref = new swing.Button();
        addb = new swing.Button();
        upb = new swing.Button();
        delb = new swing.Button();
        canb = new swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(225, 223, 228));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 35)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(114, 114, 114));
        jLabel4.setText("Youthify");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addContainerGap(834, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fname.setLabelText("First Name");

        lname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lname.setLabelText("Last Name");
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });

        eml.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eml.setLabelText("Email");

        uname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uname.setLabelText("Username");

        ps.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ps.setLabelText("Password");
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });

        role.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));
        role.setSelectedIndex(-1);
        role.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        role.setLabeText("Select Role");
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });

        us.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "In-Active" }));
        us.setSelectedIndex(-1);
        us.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        us.setLabeText("User Status");

        uid.setEnabled(false);
        uid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uid.setLabelText("User ID:");

        ref.setBackground(new java.awt.Color(223, 120, 141));
        ref.setForeground(new java.awt.Color(114, 114, 114));
        ref.setText("REFRESH");
        ref.setAutoscrolls(true);
        ref.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        ref.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refMouseExited(evt);
            }
        });
        ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refActionPerformed(evt);
            }
        });

        addb.setBackground(new java.awt.Color(223, 120, 141));
        addb.setForeground(new java.awt.Color(114, 114, 114));
        addb.setText("ADD");
        addb.setAutoscrolls(true);
        addb.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        addb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addbMouseExited(evt);
            }
        });
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });

        upb.setBackground(new java.awt.Color(223, 120, 141));
        upb.setForeground(new java.awt.Color(114, 114, 114));
        upb.setText("UPDATE");
        upb.setAutoscrolls(true);
        upb.setEnabled(false);
        upb.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        upb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upbMouseExited(evt);
            }
        });
        upb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upbActionPerformed(evt);
            }
        });

        delb.setBackground(new java.awt.Color(223, 120, 141));
        delb.setForeground(new java.awt.Color(114, 114, 114));
        delb.setText("DELETE");
        delb.setAutoscrolls(true);
        delb.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        delb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delbMouseExited(evt);
            }
        });
        delb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbActionPerformed(evt);
            }
        });

        canb.setBackground(new java.awt.Color(223, 120, 141));
        canb.setForeground(new java.awt.Color(114, 114, 114));
        canb.setText("CANCEL");
        canb.setAutoscrolls(true);
        canb.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        canb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                canbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                canbMouseExited(evt);
            }
        });
        canb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ref, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(role, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(eml, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                            .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(ps, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(eml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(addb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(upb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(delb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(canb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addComponent(us, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel1.add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 690, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1018, 647));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psActionPerformed

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed

        if(fname.getText().isEmpty()||lname.getText().isEmpty()||eml.getText().isEmpty()||uname.getText().isEmpty()||ps.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All Feilds are required!");
            return;
        }else if(ps.getText().length()<8){
            JOptionPane.showMessageDialog(null, "Password must be 8 characters above!");
            ps.setText("");
            return;
        }else if(duplicatedChecker()){
            System.out.println("Duplicate Exist");
            return;
        }else{

            dbConnector dbc = new dbConnector();
            if (dbc.insertData("INSERT INTO tbl_users (u_fname, u_lname, u_email, u_username, u_password, u_role, u_status) "
                + "VALUES ('" + fname.getText() + "','" + lname.getText() + "','" + eml.getText() + "','"
                + uname.getText() + "','" + ps.getText() + "','" + role.getSelectedItem() + "','"+us.getSelectedItem()+"')"))
        {
            JOptionPane.showMessageDialog(null, "Inserted Successfully!");
            usersform uf = new usersform();
            uf.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Connection Error!");
        }

        }
    }//GEN-LAST:event_addbActionPerformed

    private void addbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbMouseExited
        addb.setBackground(new java.awt.Color(223,120,141));
    }//GEN-LAST:event_addbMouseExited

    private void addbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbMouseEntered
        addb.setBackground(new java.awt.Color(205, 13, 50));
    }//GEN-LAST:event_addbMouseEntered

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void refMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refMouseEntered
        ref.setBackground(new java.awt.Color(205, 13, 50));
    }//GEN-LAST:event_refMouseEntered

    private void refMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refMouseExited
        ref.setBackground(new java.awt.Color(223,120,141));
    }//GEN-LAST:event_refMouseExited

    private void refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refActionPerformed

    private void upbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upbMouseEntered
        upb.setBackground(new java.awt.Color(205, 13, 50));
    }//GEN-LAST:event_upbMouseEntered

    private void upbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upbMouseExited
        upb.setBackground(new java.awt.Color(223,120,141));
    }//GEN-LAST:event_upbMouseExited

    private void upbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upbActionPerformed
        
        if(fname.getText().isEmpty()||lname.getText().isEmpty()||eml.getText().isEmpty()||uname.getText().isEmpty()||ps.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"All Fields are required!");
    } else if(ps.getText().length()<8){
        JOptionPane.showMessageDialog(null,"Password character should be 8 above");
        ps.setText("");
    } else if(updateCheck()){
        System.out.println("Duplicate Exists");
    } else {
    
        dbConnector dbc = new dbConnector();
        
        dbc.updateData("UPDATE tbl_users SET u_fname = '"+fname.getText()+"',u_lname = '"+lname.getText()+"'"
                + ",u_email = '"+eml.getText()+"',u_username = '"+uname.getText()+"',u_password = '"+ps.getText()+"'"
                + ",u_role = '"+role.getSelectedItem()+"',u_status = '"+us.getSelectedItem()+"' WHERE u_id ='"+uid.getText()+"'");
        
        usersform uf = new usersform();
        uf.setVisible(true);
        this.dispose();
    }
        
    }//GEN-LAST:event_upbActionPerformed

    private void delbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delbMouseEntered
        delb.setBackground(new java.awt.Color(205, 13, 50));
    }//GEN-LAST:event_delbMouseEntered

    private void delbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delbMouseExited
        delb.setBackground(new java.awt.Color(223,120,141));
    }//GEN-LAST:event_delbMouseExited

    private void delbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delbActionPerformed

    private void canbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canbMouseEntered
        canb.setBackground(new java.awt.Color(205, 13, 50));
    }//GEN-LAST:event_canbMouseEntered

    private void canbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canbMouseExited
        canb.setBackground(new java.awt.Color(223,120,141));
    }//GEN-LAST:event_canbMouseExited

    private void canbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canbActionPerformed
        usersform uf = new usersform();
        uf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_canbActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createuserforms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createuserforms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createuserforms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createuserforms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createuserforms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public swing.Button addb;
    private swing.Button canb;
    private swing.Button delb;
    public swing.TextField eml;
    public swing.TextField fname;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public swing.TextField lname;
    private swing.PanelBorder panelBorder1;
    public swing.PasswordField ps;
    private swing.Button ref;
    public swing.Combobox role;
    public swing.TextField uid;
    public swing.TextField uname;
    public swing.Button upb;
    public swing.Combobox us;
    // End of variables declaration//GEN-END:variables
}
