package admindash;

import javax.swing.Timer;
import java.awt.Dimension;
import swing.Button;

public class userbutton extends javax.swing.JPanel {

    private boolean isExpanded = false;
    private Timer timer;

    public userbutton() {
        initComponents(); // Initialize components first
    System.out.println("button1: " + viewusers); // Debugging
    viewusers.setVisible(false);
    viewusers.setPreferredSize(new Dimension(200, 0));
    }

    private void toggleButton1() {
    int width = viewusers.getPreferredSize().width; // ✅ Fixed: Use viewusers

    if (isExpanded) { 
        timer = new Timer(5, e -> {
            int height = viewusers.getPreferredSize().height;
            if (height > 0) {
                viewusers.setPreferredSize(new Dimension(width, height - 5));
                viewusers.revalidate();
                viewusers.repaint();
            } else {
                ((Timer) e.getSource()).stop();
                viewusers.setVisible(false);
                isExpanded = false;
            }
        });
    } else {
        viewusers.setVisible(true);
        timer = new Timer(5, e -> {
            int height = viewusers.getPreferredSize().height;
            if (height < 40) { 
                viewusers.setPreferredSize(new Dimension(width, height + 5));
                viewusers.revalidate();
                viewusers.repaint();
            } else {
                ((Timer) e.getSource()).stop();
                isExpanded = true;
            }
        });
    }
    timer.start();
}



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view = new swing.Button();
        viewusers = new swing.Button();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(230, 83));

        view.setBackground(new java.awt.Color(223, 120, 141));
        view.setForeground(new java.awt.Color(114, 114, 114));
        view.setText("User");
        view.setAutoscrolls(true);
        view.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewMouseExited(evt);
            }
        });
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        viewusers.setBackground(new java.awt.Color(223, 120, 141));
        viewusers.setForeground(new java.awt.Color(114, 114, 114));
        viewusers.setText("Users");
        viewusers.setAutoscrolls(true);
        viewusers.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        viewusers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewusersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewusersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewusersMouseExited(evt);
            }
        });
        viewusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewusersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewusers, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewusers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseEntered
        view.setBackground(new java.awt.Color(205, 13, 50));
    }//GEN-LAST:event_viewMouseEntered

    private void viewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseExited
        view.setBackground(new java.awt.Color(223,120,141));
    }//GEN-LAST:event_viewMouseExited

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        toggleButton1();
    }//GEN-LAST:event_viewActionPerformed

    private void viewusersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewusersMouseEntered
        viewusers.setBackground(new java.awt.Color(205, 13, 50)); // 
    }//GEN-LAST:event_viewusersMouseEntered

    private void viewusersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewusersMouseExited
        viewusers.setBackground(new java.awt.Color(223,120,141)); // ✅ Corrected
    }//GEN-LAST:event_viewusersMouseExited

    private void viewusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewusersActionPerformed
        isExpanded = false; 
        toggleButton1(); 
    }//GEN-LAST:event_viewusersActionPerformed

    private void viewusersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewusersMouseClicked
        usersform uf = new usersform();
        uf.setVisible(true);
        this.disable();
    }//GEN-LAST:event_viewusersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button view;
    private swing.Button viewusers;
    // End of variables declaration//GEN-END:variables
}
